package com.example.themepractice.ui.theme

import androidx.compose.ui.graphics.Color

// Deep teal seed: #006A60. Generated with Google's Material color utilities.
val LightPrimary = Color(0xFF006A60)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF74F8E6)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF4A635F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E2)
val LightOnSecondaryContainer = Color(0xFF05201C)
val LightTertiary = Color(0xFF466179)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCCE5FF)
val LightOnTertiaryContainer = Color(0xFF001D31)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFAFDFB)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFDFB)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDAE5E2)
val LightOnSurfaceVariant = Color(0xFF3F4947)
val LightOutline = Color(0xFF6F7977)

val DarkPrimary = Color(0xFF53DBCA)
val DarkOnPrimary = Color(0xFF003732)
val DarkPrimaryContainer = Color(0xFF005048)
val DarkOnPrimaryContainer = Color(0xFF74F8E6)
val DarkSecondary = Color(0xFFB1CCC6)
val DarkOnSecondary = Color(0xFF1C3531)
val DarkSecondaryContainer = Color(0xFF334B47)
val DarkOnSecondaryContainer = Color(0xFFCCE8E2)
val DarkTertiary = Color(0xFFADCAE6)
val DarkOnTertiary = Color(0xFF153349)
val DarkTertiaryContainer = Color(0xFF2D4961)
val DarkOnTertiaryContainer = Color(0xFFCCE5FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkBackground = Color(0xFF191C1B)
val DarkOnBackground = Color(0xFFE0E3E1)
val DarkSurface = Color(0xFF191C1B)
val DarkOnSurface = Color(0xFFE0E3E1)
val DarkSurfaceVariant = Color(0xFF3F4947)
val DarkOnSurfaceVariant = Color(0xFFBEC9C6)
val DarkOutline = Color(0xFF899390)
